name: Pipeline

on:
  push:
    branches:
      - master
env:
  APPLICATION_NAME: app_code

jobs:
  lint:
    name: linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python environment
      uses: actions/setup-python@v3
    - name: Install requirements
      run: pip install --quiet --requirement requirements.txt
    # code  liniting
    - name: Lint code
      run: |
        flake8 --ignore=E501,E231 *.py
        pylint --disable=C0301 --disable=C0326 *.py
    # run unit test
    - name: Run unit tests
      run: python -m unittest --verbose --failfast