name: Pipeline

on:
  push:
    branches:
      - main
      - master
env:
  APPLICATION_NAME: app_code

jobs:
  lint:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v3
      - name: Install requirements
        run: pip install --quiet --requirement requirements.txt
      # code  liniting
      - name: Lint code
        run: |
          flake8 --ignore=E501,E231,W293,F841,W292 *.py
          pylint --disable=C0301 --disable=C0326 --disable=W0718 *.py
      # run unit test
      - name: Run unit tests
        run: python -m unittest --verbose --failfast

  build_image:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_PASS }}

        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS

      - name: docker-image-build
        run: docker build --file Dockerfile --tag soutrik71/pywebapp:v0.1 .

      - name: docker image push
        run: docker push soutrik71/pywebapp:v0.1


  test_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests in container
        run: docker run soutrik71/pywebapp:v0.1 -m unittest --verbose --failfast
